# These are supported funding model platforms

github: [yaox2689-max]
# patreon:
# open_collective:
# ko_fi:
# tidelift:
# community_bridge:
# liberapay:
# issuehunt:
# otechie:
# lfx_crowdfunding:
# custom:
